// swift-tools-version: 6.0
import PackageDescription

let package = Package(
  name: "unite-analysis-swift",
  platforms: [.macOS("26.0")],
  products: [
    .executable(name: "unite-analysis-swift", targets: ["UniteAnalysisSwiftTool"])
  ],
  dependencies: [
    .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.8.2")
  ],
  targets: [
    .target(
      name: "OpenCVCore",
      path: "Vendor",
      exclude: ["opencv/samples"],
      sources: [
        "opencv/modules/core/src/algorithm.cpp",
        "opencv/modules/core/src/alloc.cpp",
        "opencv/modules/core/src/arithm.cpp",
        "opencv/modules/core/src/arithm.dispatch.cpp",
        "opencv/modules/core/src/async.cpp",
        "opencv/modules/core/src/batch_distance.cpp",
        "opencv/modules/core/src/bindings_utils.cpp",
        "opencv/modules/core/src/buffer_area.cpp",
        "opencv/modules/core/src/channels.cpp",
        "opencv/modules/core/src/check.cpp",
        "opencv/modules/core/src/command_line_parser.cpp",
        "opencv/modules/core/src/conjugate_gradient.cpp",
        "opencv/modules/core/src/convert.dispatch.cpp",
        "opencv/modules/core/src/convert_scale.dispatch.cpp",
        "opencv/modules/core/src/copy.cpp",
        "opencv/modules/core/src/count_non_zero.dispatch.cpp",
        "opencv/modules/core/src/downhill_simplex.cpp",
        "opencv/modules/core/src/dxt.cpp",
        "opencv/modules/core/src/glob.cpp",
        "opencv/modules/core/src/hal_internal.cpp",
        "opencv/modules/core/src/has_non_zero.dispatch.cpp",
        "opencv/modules/core/src/kmeans.cpp",
        "opencv/modules/core/src/lapack.cpp",
        "opencv/modules/core/src/lda.cpp",
        "opencv/modules/core/src/logger.cpp",
        "opencv/modules/core/src/lpsolver.cpp",
        "opencv/modules/core/src/lut.cpp",
        "opencv/modules/core/src/mathfuncs.cpp",
        "opencv/modules/core/src/mathfuncs_core.dispatch.cpp",
        "opencv/modules/core/src/matmul.dispatch.cpp",
        "opencv/modules/core/src/matrix.cpp",
        "opencv/modules/core/src/matrix_decomp.cpp",
        "opencv/modules/core/src/matrix_expressions.cpp",
        "opencv/modules/core/src/matrix_iterator.cpp",
        "opencv/modules/core/src/matrix_operations.cpp",
        "opencv/modules/core/src/matrix_sparse.cpp",
        "opencv/modules/core/src/matrix_transform.cpp",
        "opencv/modules/core/src/matrix_wrap.cpp",
        "opencv/modules/core/src/mean.dispatch.cpp",
        "opencv/modules/core/src/merge.dispatch.cpp",
        "opencv/modules/core/src/minmax.dispatch.cpp",
        "opencv/modules/core/src/nan_mask.dispatch.cpp",
        "opencv/modules/core/src/norm.dispatch.cpp",
        "opencv/modules/core/src/ocl.cpp",
        "opencv/modules/core/src/out.cpp",
        "opencv/modules/core/src/parallel.cpp",
        "opencv/modules/core/src/parallel/parallel.cpp",
        "opencv/modules/core/src/parallel_impl.cpp",
        "opencv/modules/core/src/pca.cpp",
        "opencv/modules/core/src/persistence.cpp",
        "opencv/modules/core/src/persistence_base64_encoding.cpp",
        "opencv/modules/core/src/persistence_json.cpp",
        "opencv/modules/core/src/persistence_types.cpp",
        "opencv/modules/core/src/persistence_xml.cpp",
        "opencv/modules/core/src/persistence_yml.cpp",
        "opencv/modules/core/src/rand.cpp",
        "opencv/modules/core/src/reduce.dispatch.cpp",
        "opencv/modules/core/src/softfloat.cpp",
        "opencv/modules/core/src/split.dispatch.cpp",
        "opencv/modules/core/src/stat.dispatch.cpp",
        "opencv/modules/core/src/stl.cpp",
        "opencv/modules/core/src/sum.dispatch.cpp",
        "opencv/modules/core/src/system.cpp",
        "opencv/modules/core/src/tables.cpp",
        "opencv/modules/core/src/trace.cpp",
        "opencv/modules/core/src/types.cpp",
        "opencv/modules/core/src/umatrix.cpp",
        "opencv/modules/core/src/utils/filesystem.cpp",
        "opencv/modules/core/src/utils/logtagconfigparser.cpp",
        "opencv/modules/core/src/utils/logtagmanager.cpp",
      ],
      publicHeadersPath: "opencv/modules/core/include",
      cxxSettings: [
        .headerSearchPath("opencv-config/include"),
        .define("__OPENCV_BUILD", to: "1"),
      ],
      linkerSettings: [
        .linkedFramework("Accelerate"), .linkedLibrary("z"),
      ]
    ),
    .target(
      name: "OpenCVAKAZE",
      dependencies: ["OpenCVCore"],
      path: "Vendor",
      exclude: ["opencv/samples"],
      sources: [
        "opencv/modules/imgproc/src/box_filter.dispatch.cpp",
        "opencv/modules/imgproc/src/color.cpp",
        "opencv/modules/imgproc/src/color_hsv.dispatch.cpp",
        "opencv/modules/imgproc/src/color_lab.cpp",
        "opencv/modules/imgproc/src/color_rgb.dispatch.cpp",
        "opencv/modules/imgproc/src/color_yuv.dispatch.cpp",
        "opencv/modules/imgproc/src/demosaicing.cpp",
        "opencv/modules/imgproc/src/deriv.cpp",
        "opencv/modules/imgproc/src/filter.dispatch.cpp",
        "opencv/modules/imgproc/src/resize.cpp",
        "opencv/modules/imgproc/src/smooth.dispatch.cpp",
        "opencv/modules/imgproc/src/sumpixels.dispatch.cpp",
        "opencv/modules/imgproc/src/tables.cpp",
        "opencv/modules/imgproc/src/templmatch.cpp",
        "opencv/modules/imgproc/src/thresh.cpp",
        "opencv/modules/features/src/feature2d.cpp",
        "opencv/modules/features/src/keypoint.cpp",
        "opencv/modules/features/src/matchers.cpp",
        "opencv_contrib/modules/xfeatures2d/src/akaze.cpp",
        "opencv_contrib/modules/xfeatures2d/src/kaze/AKAZEFeatures.cpp",
        "opencv_contrib/modules/xfeatures2d/src/kaze/fed.cpp",
        "opencv_contrib/modules/xfeatures2d/src/kaze/nldiffusion_functions.cpp",
      ],
      publicHeadersPath: "opencv_contrib/modules/xfeatures2d/include",
      cxxSettings: [
        .headerSearchPath("opencv-config/include"),
        .headerSearchPath("opencv/modules/imgproc/include"),
        .headerSearchPath("opencv/modules/geometry/include"),
        .headerSearchPath("opencv/modules/features/include"),
        .define("__OPENCV_BUILD", to: "1"),
      ]
    ),
    .target(
      name: "Nanopb",
      path: "Vendor/nanopb",
      sources: ["pb_common.c", "pb_decode.c"],
      publicHeadersPath: "spm_headers",
      cSettings: [
        .define("PB_FIELD_32BIT", to: "1"),
        .define("PB_NO_PACKED_STRUCTS", to: "1"),
      ]
    ),
    .target(
      name: "IconMatcherNative",
      dependencies: ["OpenCVAKAZE", "Nanopb"],
      path: ".",
      exclude: ["Vendor/opencv/samples"],
      sources: ["Sources/IconMatcherNative"],
      publicHeadersPath: "Sources/IconMatcherNative/include",
      cSettings: [
        .define("PB_FIELD_32BIT", to: "1"),
        .define("PB_NO_PACKED_STRUCTS", to: "1"),
      ],
      cxxSettings: [
        .define("PB_FIELD_32BIT", to: "1"),
        .define("PB_NO_PACKED_STRUCTS", to: "1"),
        .headerSearchPath("Sources/IconMatcherNative/Generated"),
        .headerSearchPath("Vendor/opencv-config/include"),
        .headerSearchPath("Vendor/opencv/modules/imgproc/include"),
        .headerSearchPath("Vendor/opencv/modules/features/include"),
        .headerSearchPath("Vendor/opencv_contrib/modules/xfeatures2d/include"),
      ]
    ),
    .target(name: "LDTXRecordingSupport"),
    .target(
      name: "ResultScannerSupport",
      path: "Sources/ResultScanner"
    ),
    .target(name: "RecordVisionSupport", dependencies: ["LDTXRecordingSupport"]),
    .target(name: "UniteAnalysisConfiguration"),
    .executableTarget(
      name: "UniteAnalysisSwiftTool",
      dependencies: [
        "LDTXRecordingSupport",
        "RecordVisionSupport",
        "ResultScannerSupport",
        "UniteAnalysisConfiguration",
        "IconMatcherNative",
        .product(name: "ArgumentParser", package: "swift-argument-parser"),
      ],
      swiftSettings: [.interoperabilityMode(.Cxx)]),
    .testTarget(
      name: "LDTXRecordingSupportTests",
      dependencies: [
        "LDTXRecordingSupport", "RecordVisionSupport", "ResultScannerSupport",
        "UniteAnalysisConfiguration", "UniteAnalysisSwiftTool", "IconMatcherNative",
      ],
      swiftSettings: [.interoperabilityMode(.Cxx)]),
  ],
  cxxLanguageStandard: .cxx17
)
