version = 1

[[annotations]]
path = [".gitattributes", ".gitmodules", ".swift-format", "NOTICE"]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "Package.resolved",
  "Package.swift",
  "Packaging/App/Info.plist",
  "docs/*.json",
  "docs/metadata/*",
  "Sources/IconMatcherNative/Generated/*.pb.c",
  "Sources/IconMatcherNative/Generated/*.pb.h",
]
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "Apache-2.0"
