# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: PR

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-ci:
    permissions:
      contents: read
    uses: ./.github/workflows/check-ci.yml

  swift-ci:
    permissions:
      contents: read
    uses: ./.github/workflows/swift.yml
